# Day 1

### Importing the data 

Link to data - https://www.kaggle.com/datasets/alfathterry/bbc-full-text-document-classification?resource=download

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('bbc_data.csv')

In [3]:
df

                                                   data         labels
0     Musicians to tackle US red tape  Musicians gro...  entertainment
1     U2s desire to be number one  U2, who have won ...  entertainment
2     Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3     Snicket tops US box office chart  The film ada...  entertainment
4     Oceans Twelve raids box office  Oceans Twelve,...  entertainment
...                                                 ...            ...
2220  Warning over Windows Word files  Writing a Mic...           tech
2221  Fast lifts rise into record books  Two high-sp...           tech
2222  Nintendo adds media playing to DS  Nintendo is...           tech
2223  Fast moving phone viruses appear  Security fir...           tech
2224  Hacker threat to Apples iTunes  Users of Apple...           tech

[2225 rows x 2 columns]

In [4]:
df['labels'].unique()

array(['entertainment', 'business', 'sport', 'politics', 'tech'],
      dtype=object)

In [5]:
df['labels'].nunique()

5

In [7]:
df['data'].nunique()

2126

In [6]:
df[['data','labels']].drop_duplicates()

                                                   data         labels
0     Musicians to tackle US red tape  Musicians gro...  entertainment
1     U2s desire to be number one  U2, who have won ...  entertainment
2     Rocker Doherty in on-stage fight  Rock singer ...  entertainment
3     Snicket tops US box office chart  The film ada...  entertainment
4     Oceans Twelve raids box office  Oceans Twelve,...  entertainment
...                                                 ...            ...
2220  Warning over Windows Word files  Writing a Mic...           tech
2221  Fast lifts rise into record books  Two high-sp...           tech
2222  Nintendo adds media playing to DS  Nintendo is...           tech
2223  Fast moving phone viruses appear  Security fir...           tech
2224  Hacker threat to Apples iTunes  Users of Apple...           tech

[2126 rows x 2 columns]

In [8]:
df.isna().sum()

data      0
labels    0
dtype: int64

In [9]:
df['labels'].value_counts()

labels
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [10]:
l = [1,2.,1,8,9]

In [11]:
dir(l)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [12]:
l.remove(1)

In [13]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'data',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'labels',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

# Day 2

## Prepping the data

### Converting all the text column to lower case

In [14]:
df['data'] = df['data'].str.lower()

In [15]:
df

                                                   data         labels
0     musicians to tackle us red tape  musicians gro...  entertainment
1     u2s desire to be number one  u2, who have won ...  entertainment
2     rocker doherty in on-stage fight  rock singer ...  entertainment
3     snicket tops us box office chart  the film ada...  entertainment
4     oceans twelve raids box office  oceans twelve,...  entertainment
...                                                 ...            ...
2220  warning over windows word files  writing a mic...           tech
2221  fast lifts rise into record books  two high-sp...           tech
2222  nintendo adds media playing to ds  nintendo is...           tech
2223  fast moving phone viruses appear  security fir...           tech
2224  hacker threat to apples itunes  users of apple...           tech

[2225 rows x 2 columns]

### Import spacy for other text cleaning purposes

In [16]:
! pip install spacy

Requirement already satisfied: spacy in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (3.8.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.2.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.10.5)
Requirement already satisfied: jinja2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.1.5)
Requirement already satisfied: setuptools in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.12.14)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.2.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: wrapt in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\narla\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [17]:
import spacy

# Download the spaCy model
!python -m spacy download en_core_web_sm

# Load the spaCy model
nlp = spacy.load('en_core_web_sm')

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ------------- -------------------------- 4.2/12.8 MB 62.4 MB/s eta 0:00:01
     ------------------------------ -------- 10.0/12.8 MB 28.2 MB/s eta 0:00:01
     ------------------------------ -------- 10.0/12.8 MB 28.2 MB/s eta 0:00:01
     --------------------------------------- 12.8/12.8 MB 16.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

### Remove Punctuations

In [18]:
df['data'] = df['data'].str.replace(',', ' ')
df['data'] = df['data'].str.replace('.', ' ')
df['data'] = df['data'].str.replace('-', ' ')
df['data'] = df['data'].str.replace('"', ' ')
df['data'] = df['data'].str.replace('  ',' ')

In [19]:
df

                                                   data         labels
0     musicians to tackle us red tape musicians grou...  entertainment
1     u2s desire to be number one u2 who have won th...  entertainment
2     rocker doherty in on stage fight rock singer p...  entertainment
3     snicket tops us box office chart the film adap...  entertainment
4     oceans twelve raids box office oceans twelve t...  entertainment
...                                                 ...            ...
2220  warning over windows word files writing a micr...           tech
2221  fast lifts rise into record books two high spe...           tech
2222  nintendo adds media playing to ds nintendo is ...           tech
2223  fast moving phone viruses appear security firm...           tech
2224  hacker threat to apples itunes users of apples...           tech

[2225 rows x 2 columns]

### Remove stop words

In [20]:
stop_words = ['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 
              'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but',
               'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing',
               'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn',
               "hasn't", 'have', 'haven', "haven't", 'having', 'he', 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his',
               'how', 'i', 'if', 'in', 'into', 'is', 'isn', "isn't", 'it', "it's", 'its', 'itself', 'just', 'll', 'm', 'ma', 'me',
               'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'now', 'o', 'of',
               'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan',
               "shan't", 'she', "she's", 'should', "should've", 'shouldn', "shouldn't", 'so', 'some', 'such', 't', 'than', 'that',
               "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', 'this', 'those', 'through',
               'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', 'were', 'weren', "weren't", 'what',
               'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y',
               'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself', 'yourselves']

In [21]:
def stop_word_removal(text):
    tokens = text.split(' ')
    words_without_stopwords = [x for x in tokens if x not in stop_words]
    final_sentence = ' '.join(words_without_stopwords)
    return final_sentence

In [22]:
df['clean_data'] = df['data'].apply(stop_word_removal)

In [23]:
df

,data,labels,clean_data
0,musicians to tackle us red tape musicians grou...,entertainment,musicians tackle us red tape musicians groups ...
1,u2s desire to be number one u2 who have won th...,entertainment,u2s desire number one u2 three prestigious gra...
2,rocker doherty in on stage fight rock singer p...,entertainment,rocker doherty stage fight rock singer pete do...
3,snicket tops us box office chart the film adap...,entertainment,snicket tops us box office chart film adaptati...
4,oceans twelve raids box office oceans twelve t...,entertainment,oceans twelve raids box office oceans twelve c...
...,...,...,...
2220,warning over windows word files writing a micr...,tech,warning windows word files writing microsoft w...
2221,fast lifts rise into record books two high spe...,tech,fast lifts rise record books two high speed li...
2222,nintendo adds media playing to ds nintendo is ...,tech,nintendo adds media playing ds nintendo releas...
2223,fast moving phone viruses appear security firm...,tech,fast moving phone viruses appear security firm...
2224,hacker threat to apples itunes users of apples...,tech,hacker threat apples itunes users apples music...

### Get the vector embeddings

In [24]:
def get_embeddings(text):
    doc = nlp(text)
    return doc.vector

In [25]:
df["embeddings"] = df["clean_data"].apply(get_embeddings)

In [26]:
df

,data,labels,clean_data,embeddings
0,musicians to tackle us red tape musicians grou...,entertainment,musicians tackle us red tape musicians groups ...,"[0.2015061, -0.20731805, -0.29421645, -0.03264..."
1,u2s desire to be number one u2 who have won th...,entertainment,u2s desire number one u2 three prestigious gra...,"[0.28642786, -0.2850171, -0.10007215, -0.08766..."
2,rocker doherty in on stage fight rock singer p...,entertainment,rocker doherty stage fight rock singer pete do...,"[0.3285009, -0.24485895, -0.13713713, -0.08740..."
3,snicket tops us box office chart the film adap...,entertainment,snicket tops us box office chart film adaptati...,"[0.21824618, -0.22423987, 0.031301666, 0.05396..."
4,oceans twelve raids box office oceans twelve t...,entertainment,oceans twelve raids box office oceans twelve c...,"[0.1465682, -0.23421904, 0.02751773, 0.0523804..."
...,...,...,...,...
2220,warning over windows word files writing a micr...,tech,warning windows word files writing microsoft w...,"[0.3579604, -0.124646805, -0.16185522, -0.1154..."
2221,fast lifts rise into record books two high spe...,tech,fast lifts rise record books two high speed li...,"[0.26983613, -0.12480863, -0.065554865, -0.099..."
2222,nintendo adds media playing to ds nintendo is ...,tech,nintendo adds media playing ds nintendo releas...,"[0.25802773, -0.32408676, -0.06167393, -0.0253..."
2223,fast moving phone viruses appear security firm...,tech,fast moving phone viruses appear security firm...,"[0.3159842, -0.27449182, -0.049973343, -0.0783..."
2224,hacker threat to apples itunes users of apples...,tech,hacker threat apples itunes users apples music...,"[0.16901626, -0.10892734, -0.10707976, -0.0015..."

In [27]:
np.vstack(df["embeddings"].values).shape

(2225, 96)

In [28]:
s = 'Hi This is a test sentence .check if the stop words.  end sentence'
s.split('.')

['Hi This is a test sentence ', 'check if the stop words', '  end sentence']

In [29]:
a="""Hi this is the sample to verify stop words removal.
    This is a test sentence. Check if the stop words are removed.
    End of the sentence.
    """
a.split('\n')

['Hi this is the sample to verify stop words removal.',
 '    This is a test sentence. Check if the stop words are removed.',
 '    End of the sentence.',
 '    ']

In [30]:
a.split(' ')

['Hi',
 'this',
 'is',
 'the',
 'sample',
 'to',
 'verify',
 'stop',
 'words',
 'removal.\n',
 '',
 '',
 '',
 'This',
 'is',
 'a',
 'test',
 'sentence.',
 'Check',
 'if',
 'the',
 'stop',
 'words',
 'are',
 'removed.\n',
 '',
 '',
 '',
 'End',
 'of',
 'the',
 'sentence.\n',
 '',
 '',
 '',
 '']

In [31]:
''.join(a.split('\n'))

'Hi this is the sample to verify stop words removal.    This is a test sentence. Check if the stop words are removed.    End of the sentence.    '